### ISSUE TITLE
Would that be an app?

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraRelay#1]
Hello!:)

Any live demos? or screenshot?
Would that be an app?

**Comment by afonsosantos** [comment]
Not sure what you mean by `app`...

**Comment by Rafaelrds2017** [comment]
OK thank you for the attention

**Comment by pwrj** [comment]
I followed the install instructions and it wipeout my station #2
ERROR: The Compose file is invalid because:
Service stations has neither an image nor a build context specified. At least one must be provided.

**Comment by Vaalyn** [comment]
> Any live demos? or screenshot?

It may make sense to have one relay set up for the demo installation so that you can look at the `Connected AzuraRelays` page so that we can demonstrate that feature there.

Regarding screenshots I think there is not much we can show here as the relay itself has no real GUI for anything. We could add a screenshot of the page I mentioned.

> Would that be an app?

Please clarify what you mean here. I'm not sure what you are asking.
