### ISSUE TITLE
Slim Application Error on index page

### ISSUE THREAD

**Issue by EmpressFiona** [AzuraCast/AzuraRelay#15]
I'm uncertain if this is an 'error' or 'bug' as such, or if this is intended and there isn't supposed to be a front-facing page on the relay, but this is all I see when I open up my AzuraRelay in the browser:

![image](https://user-images.githubusercontent.com/17802496/102975729-7f9ed700-44ce-11eb-89f2-b44ccfcc2c03.png)

The streams all work fine, though.

I was hoping to set up a page that only used the relay as public-facing website, with the instance on my backend server isolated because of its low bandwidth; as it is, I have no web-ui 'frontend', nor can I even select relays as the default for the public AzuraCast page player. (This also means I can't present the on-demand service from the 'frontend' AzuraRelay, either.)

Barring something being broken, any suggestions for how to set up the public face? Will AzuraRelay break if I replace the index page with another one?

**Comment by EmpressFiona** [comment]
As a note, though: I took the container up and down repeatedly to test, and I *very* quickly ran into an issue where my certificates kept being overwritten and I reached my rate limit for certs.

I might have backups from previous attempts, and the frontend doesn't necessarily *need* HTTPS access, but that's a fairly big design flaw. (I don't know if it's on your end or upstream in the nginx proxy, though.)

**Comment by SlvrEagle23** [comment]
@EmpressFiona If you check the logs (in this case, it should be by running `docker-compose logs -f relay` on the host) when visiting the index page, do you see the error in more detail?

**Comment by tzerber** [comment]
`[2021-01-15T10:11:21.058726+00:00] AzuraRelay.ERROR: Slim Application Error Type: TypeError Code: 0 Message: Argument 1 passed to App\Http\Router::__construct() must implement interface Slim\Interfaces\RouteParserInterface, instance of App\Environment given, called in /var/azurarelay/www_tmp/CompiledContainer.php on line 22 File: /var/azurarelay/www/src/Http/Router.php Line: 21 Trace: #0 /var/azurarelay/www_tmp/CompiledContainer.php(22): App\Http\Router->__construct() #1 [internal function]: CompiledContainer::{closure}() #2 /var/azurarelay/www/vendor/php-di/invoker/src/Invoker.php(75): call_user_func_array() #3 /var/azurarelay/www/vendor/php-di/php-di/src/CompiledContainer.php(116): Invoker\Invoker->call() #4 /var/azurarelay/www_tmp/CompiledContainer.php(23): DI\CompiledContainer->resolveFactory() #5 /var/azurarelay/www/vendor/php-di/php-di/src/CompiledContainer.php(53): CompiledContainer->get1() #6 /var/azurarelay/www_tmp/CompiledContainer.php(28): DI\CompiledContainer->get() #7 /var/azurarelay/www/vendor/php-di/php-di/src/CompiledContainer.php(53): CompiledContainer->get2() #8 /var/azurarelay/www/vendor/php-di/php-di/src/Definition/Reference.php(53): DI\CompiledContainer->get() #9 /var/azurarelay/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(66): DI\Definition\Reference->resolve() #10 /var/azurarelay/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(78): DI\Definition\Resolver\ResolverDispatcher->resolve() #11 /var/azurarelay/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(138): DI\Definition\Resolver\ParameterResolver->resolveParameters() #12 /var/azurarelay/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance() #13 /var/azurarelay/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\ObjectCreator->resolve() #14 /var/azurarelay/www/vendor/php-di/php-di/src/Container.php(387): DI\Definition\Resolver\ResolverDispatcher->resolve() #15 /var/azurarelay/www/vendor/php-di/php-di/src/Container.php(138): DI\Container->resolveDefinition() #16 /var/azurarelay/www/vendor/php-di/php-di/src/CompiledContainer.php(64): DI\Container->get() #17 /var/azurarelay/www/vendor/slim/slim/Slim/CallableResolver.php(144): DI\CompiledContainer->get() #18 /var/azurarelay/www/vendor/slim/slim/Slim/CallableResolver.php(101): Slim\CallableResolver->resolveSlimNotation() #19 /var/azurarelay/www/vendor/slim/slim/Slim/CallableResolver.php(79): Slim\CallableResolver->resolveByPredicate() #20 /var/azurarelay/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(208): Slim\CallableResolver->resolveMiddleware() #21 /var/azurarelay/www/vendor/slim/slim/Slim/Middleware/BodyParsingMiddleware.php(68): class@anonymous->handle() #22 /var/azurarelay/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\BodyParsingMiddleware->process() #23 /var/azurarelay/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle() #24 /var/azurarelay/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process() #25 /var/azurarelay/www/src/Middleware/RemoveSlashes.php(37): class@anonymous->handle() #26 /var/azurarelay/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): App\Middleware\RemoveSlashes->process() #27 /var/azurarelay/www/src/Middleware/ApplyXForwardedProto.php(28): class@anonymous->handle() #28 /var/azurarelay/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): App\Middleware\ApplyXForwardedProto->process() #29 /var/azurarelay/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle() #30 /var/azurarelay/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process() #31 /var/azurarelay/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle() #32 /var/azurarelay/www/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle() #33 /var/azurarelay/www/vendor/slim/slim/Slim/App.php(199): Slim\App->handle() #34 /var/azurarelay/www/web/index.php(11): Slim\App->run() #35 {main} Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.  [] []`

i'm having exactly the same problem, but i'm trying to "strip out" the letsencrypt and run only azurarelay (i have more complex use case, but that's not related to this issue.)

**Comment by SlvrEagle23** [comment]
@tzerber This suggests the `azurarelay_tmp_data` volume isn't being flushed upon an update; when it's flushed, it regenerates that compiled container file to always be the latest version alongside the code, which prevents problems like that from happening. I'd make sure you're on the very latest Docker utility script for AzuraRelay (via `./docker.sh update-self`) and make sure your modifications aren't messing with that particular functionality.

**Comment by tzerber** [comment]
> 
> 
> @tzerber This suggests the `azurarelay_tmp_data` volume isn't being flushed upon an update; when it's flushed, it regenerates that compiled container file to always be the latest version alongside the code, which prevents problems like that from happening. I'd make sure you're on the very latest Docker utility script for AzuraRelay (via `./docker.sh update-self`) and make sure your modifications aren't messing with that particular functionality.

I did update-self, then update (both via docker-sh) and got this
```

AzuraRelay Updater

 * Station-1-name-here
 * Station-2-name-here
 [OK] Update successful. Relay is functioning!
```

Still error 500 on frontend.

Then did docker.sh uninstall, removed everything, and did a fresh install. 
The only change i did to the default install is http port to 82 and https port to 444 (since they both are busy @ my server, hence the other modifications) and enter N to letsencrypt, because i don't want to issue cert on the wrong container and hit the LE limits.

Got this 
` [OK] Setup is complete!`

then this 
```
AzuraRelay Updater
==================

 * Station-1-name-here
 * Station-2-name-here
````

Web ui still giving error 500 and in app log i get this error.

`[2021-01-15T20:15:42.473576+00:00] AzuraRelay.ERROR: Slim Application Error Type: TypeError Code: 0 Message: Argument 1 passed to App\Http\Router::__construct() must implement interface Slim\Interfaces\RouteParserInterface, instance of App\Environment given, called in /var/azurarelay/www_tmp/CompiledContainer.php on line 22 File: /var/azurarelay/www/src/Http/Router.php Line: 21 Trace: #0 /var/azurarelay/www_tmp/CompiledContainer.php(22): App\Http\Router->__construct() #1 [internal function]: CompiledContainer::{closure}() #2 /var/azurarelay/www/vendor/php-di/invoker/src/Invoker.php(75): call_user_func_array() #3 /var/azurarelay/www/vendor/php-di/php-di/src/CompiledContainer.php(116): Invoker\Invoker->call() #4 /var/azurarelay/www_tmp/CompiledContainer.php(23): DI\CompiledContainer->resolveFactory() #5 /var/azurarelay/www/vendor/php-di/php-di/src/CompiledContainer.php(53): CompiledContainer->get1() #6 /var/azurarelay/www_tmp/CompiledContainer.php(28): DI\CompiledContainer->get() #7 /var/azurarelay/www/vendor/php-di/php-di/src/CompiledContainer.php(53): CompiledContainer->get2() #8 /var/azurarelay/www/vendor/php-di/php-di/src/Definition/Reference.php(53): DI\CompiledContainer->get() #9 /var/azurarelay/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(66): DI\Definition\Reference->resolve() #10 /var/azurarelay/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(78): DI\Definition\Resolver\ResolverDispatcher->resolve() #11 /var/azurarelay/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(138): DI\Definition\Resolver\ParameterResolver->resolveParameters() #12 /var/azurarelay/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance() #13 /var/azurarelay/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\ObjectCreator->resolve() #14 /var/azurarelay/www/vendor/php-di/php-di/src/Container.php(387): DI\Definition\Resolver\ResolverDispatcher->resolve() #15 /var/azurarelay/www/vendor/php-di/php-di/src/Container.php(138): DI\Container->resolveDefinition() #16 /var/azurarelay/www/vendor/php-di/php-di/src/CompiledContainer.php(64): DI\Container->get() #17 /var/azurarelay/www/vendor/slim/slim/Slim/CallableResolver.php(144): DI\CompiledContainer->get() #18 /var/azurarelay/www/vendor/slim/slim/Slim/CallableResolver.php(101): Slim\CallableResolver->resolveSlimNotation() #19 /var/azurarelay/www/vendor/slim/slim/Slim/CallableResolver.php(79): Slim\CallableResolver->resolveByPredicate() #20 /var/azurarelay/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(208): Slim\CallableResolver->resolveMiddleware() #21 /var/azurarelay/www/vendor/slim/slim/Slim/Middleware/BodyParsingMiddleware.php(68): class@anonymous->handle() #22 /var/azurarelay/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\BodyParsingMiddleware->process() #23 /var/azurarelay/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle() #24 /var/azurarelay/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process() #25 /var/azurarelay/www/src/Middleware/RemoveSlashes.php(37): class@anonymous->handle() #26 /var/azurarelay/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): App\Middleware\RemoveSlashes->process() #27 /var/azurarelay/www/src/Middleware/ApplyXForwardedProto.php(28): class@anonymous->handle() #28 /var/azurarelay/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): App\Middleware\ApplyXForwardedProto->process() #29 /var/azurarelay/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle() #30 /var/azurarelay/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process() #31 /var/azurarelay/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle() #32 /var/azurarelay/www/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle() #33 /var/azurarelay/www/vendor/slim/slim/Slim/App.php(199): Slim\App->handle() #34 /var/azurarelay/www/web/index.php(11): Slim\App->run() #35 {main} Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor. [] []
`

docker-compose logs shows this (on relay containers, others looks fine)
`relay_1                    | *** Booting runit daemon...
relay_1                    | *** Runit started as PID 6
relay_1                    | 2021-01-15 20:23:39,012 CRIT Supervisor running as root (no user in config file)
relay_1                    | 2021-01-15 20:23:39,012 WARN No file matches via include "/var/azurarelay/stations/supervisord.conf"
relay_1                    | 2021-01-15 20:23:39,012 WARN No file matches via include "/etc/supervisor/conf.d/*"
relay_1                    | 2021-01-15 20:23:39,019 INFO RPC interface 'supervisor' initialized
relay_1                    | 2021-01-15 20:23:39,019 CRIT Server 'inet_http_server' running without any HTTP authentication checking
relay_1                    | 2021-01-15 20:23:39,019 INFO RPC interface 'supervisor' initialized
relay_1                    | 2021-01-15 20:23:39,019 CRIT Server 'unix_http_server' running without any HTTP authentication checking
relay_1                    | 2021-01-15 20:23:39,019 INFO supervisord started with pid 17
relay_1                    | 2021-01-15 20:23:44,566 INFO spawned: 'station_1_relay' with pid 35
relay_1                    | 2021-01-15 20:23:44,569 INFO spawned: 'station_2_relay' with pid 36
relay_1                    | 2021-01-15 20:23:45,587 INFO success: station_1_relay entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
relay_1                    | 2021-01-15 20:23:45,587 INFO success: station_2_relay entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
`
Audio continue to work, only the frontend is erroring out. I cannot stop my other instances that run on http/https ports to try a full default install, but if the is no other option i can power up a VM and try it there.

**Comment by EmpressFiona** [comment]
> @EmpressFiona If you check the logs (in this case, it should be by running `docker-compose logs -f relay` on the host) when visiting the index page, do you see the error in more detail?

Sorry I'm late, but I don't see an error in the logs. The only error I'm getting is one about being unable to retrieve NowPlaying information from some of the mounts, but one is disabled and won't have any and the other is an Opus mount - so that's expected behaviour and not a bug.

What is the frontend supposed to look like, if I might ask? Is it a reproduction of the public page of the base AzuraCast instance? As mentioned, I'm not entirely sure that the relay is _meant_ to have a web interface of its own and that this 'error' isn't intended behaviour, in which case I'd make it a feature request instead.

**Comment by tzerber** [comment]
After some additional digging inside the source and the containers i found this inside the nginx container :
```
server {
    server_name _; # This is just an invalid value which will never trigger on a real hostname.
    listen 80;
    access_log /var/log/nginx/access.log vhost;
    return 503;
}
```
@SlvrEagle23 containers are fine, it's just that i use the app on it's http port, using nginx's upstream settings via container:port , meaning this approach will never work. I will try to fork azurarelay and modify it so it exposes the app over plain http allowing me to proxy it elsewhere.

**Comment by TechPhil** [comment]
I'm also getting this error - nothing appearing in logs, apart from the HTTP request with a 500 error code. Letsencrypt disabled and on default ports of 80 and 443, nothing else running on there.
