### ISSUE TITLE
AzuraRelay not relaying mountpoints, or adding itself as a remote relay on Azuracast

### ISSUE THREAD

**Issue by TechPhil** [AzuraCast/AzuraRelay#17]
I'm trying to set up an AzuraRelay, and it seems to pick up the mountpoints correctly, but fails to correctly relay them through IceCast, and is not registering as a connected AzuraRelay on the main AC instance

![image](https://user-images.githubusercontent.com/26381564/110691427-08c7cf00-81dd-11eb-844e-abf8a8b1c47f.png)

![image](https://user-images.githubusercontent.com/26381564/110691530-2ac15180-81dd-11eb-8b0d-47d0291fc3b1.png)

![image](https://user-images.githubusercontent.com/26381564/110691767-7542ce00-81dd-11eb-8066-8c867c23a886.png)

The mountpoints are correctly picked up in the stations.json file inside the relay container, but it seems like IceCast doesn't connect correctly. I have tried this on both standard, and custom ports, as well as both with and without Lets Encrypt.

Furthermore, I am also getting a 'Slim Application Error' on the main public-facing page - 
![image](https://user-images.githubusercontent.com/26381564/110692042-d1a5ed80-81dd-11eb-8a30-7a40f8793f2e.png)

**Comment by SlvrEagle23** [comment]
@TechPhil I've updated AzuraRelay's codebase to bring it up to par with the current AzuraCast rolling release version.

One important note: if your main installation is behind a reverse proxy like CloudFlare, you should point your AzuraRelay installation at the direct IP of the installation rather than the public-facing domain name.

**Comment by TechPhil** [comment]
This worked! Thanks to you and your team for this amazing project!
